# -*- coding: utf-8 -*-
"""IA - 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12oDi_JDzzPlHqtoL2OfLVVVK3J5q0Tft
"""

# lab 1
# 1.

length = float(input("Enter length of the space in metres: "))
width = float(input("Enter width of the space in metres: "))
area = length * width
print("Area of space = ", area)
if area > 1000:
  print("The space is very large")
elif area>500 and area<=1000:
  print("The space is of medium size")
else:
  print("The space is very small")

# 2.

weight = float(input("Enter your weight in kg: "))
height = float(input("Enter your height in metres: "))
bmi = weight/ (height*height)
print("Your Body Mass Index (BMI) is ", bmi)

# 3.

student_dict = {"Peter":{"Maths":78,"Science":65,"Social":90},
                "Patrick":{"Maths":76,"Science":75,"Social":80},
                "Robert":{"Maths":68,"Science":35,"Social":70}}

scores = dict()

operation = int(input("Enter operation to perform (1 for addition, 2 for updation, 3 for retrieval): "))
if operation == 1:
  n = int(input("Enter no. of students to add: "))
  for i in range(n):
    name = input("Enter student's name: ")
    sub = int(input("Enter no. of subjects to add: "))
    for j in range(sub):
      subject = input("Enter subject's name: ")
      marks = int(input("Enter marks scored in {}: ".format(subject)))
      scores[subject] = marks
      student_dict[name] = scores
  print("After adding: ", student_dict)

elif operation == 2:
  m = input("Enter student name to update: ")
  sub = int(input("Enter no. of subjects to update: "))
  for j in range(sub):
    subject = input("Enter subject's name: ")
    marks = int(input("Enter marks scored in {}: ".format(subject)))
    if subject == "Maths":
      index = 0
    elif subject == "Science":
      index = 1
    else:
      index = 2
    student_dict[m[index]] = marks
  print("After updation: ", student_dict)

elif operation == 3:
  m = input("Enter student name to display: ")
  print("Student report")
  print(student_dict[m])

else:
  print("Invalid operation chosen")

# lab 2
# 4

age = int(input("Enter your age: "))
if age >= 60:
  print("Senior show Recommendations")
elif age > 20:
  print("Adult show Recommendations")
elif age > 12:
  print("Teenager show Recommendations")
else:
  print("Child show Recommendations")

#5.
sub_id = [11,12,34,54,66,77,89,90,45,23]
even_sub_id = [x for x in sub_id if x%2==0]
print(even_sub_id)

# 6.
security = {"Peter":"abc","Marshal":"defg"}
user = input("Enter username:")
password = input("Enter password: ")

if i in security.keys() and j==security[i]:
  print("Login Successful")
else:
  print("Invalid username or password.Try again")

# lab 3
#7.
def customer_feedback(sat_score):
  print("Satisfaction score: ",sat_score)
  sum=0
  for i in sat_score:
    sum+=i
  print("Average of scores: ",sum/len(sat_score))
  if sum/len(sat_score) > 10:
    print("better service")
  else:
    print("Poor service")
customer_feedback([1,2,3,4,5])

#8.

def count_vowels(comment):
  vowel = 0
  for i in range(len(comment)):
    if comment[i] in ['a','e','i','o','u']:
      vowel = vowel +1
  print("Count of vowels in comment: ",vowel)
  if vowel > 10:
    print("Valid comment")
  else:
    print("Spam comment")
Comment =input("Enter your comment: ")
count_vowels(Comment)

# 9.

import datetime
datetime.

#10.

p = int(input("Enter principal amount: "))
n = int(input("No. of years: "))
r = float(input("Enter rate of interest: "))
si = (p*n*r)/100
si_amount = p+si
ci_amount = p *((1+r/100)**n)
ci = ci_amount - p
print("Simple interest : ",si,"Amount: ",si_amount)
print("Compound interest : ",ci, "Amount: ",ci_amount)

# 11.
poll = {"DMK":0,"ADMK":0,"TVK":0}
vote = input("Enter party: ")
if vote in poll.keys():
  poll[vote] = poll[vote]+1
else:
  print("Invlaid party name")
print("After voting: ",poll)

# 12.

def add(a,b):
  try:
    result = a+b
    print("Addition result = ",result)
  except TypeError:
    print("Invalid datatype given")
  finally:
    print("addition is performed")

def divi(num, deno):
  try:
    result = num/deno
    print("Division result = ",result)
  except ZeroDivisionError:
    print("Cannot divide by zero.")
  finally:
    ("Division is performed")
num = int(input("Enter number 1: "))
deno = int(input("Enter number 2: "))
add(num,deno)
divi(num,deno)

#lab 5
#13
#f = open("daily_status_report.txt","x")
f1 = open("daily_status_report.txt","w")
f1.write("Logged in at 9am. Logged out at 6pm")
f2 = open("daily_status_report.txt","r")
f2.readline()
#f1.close()

#14.
f3 = open("daily_status_report.txt","r")
f3.read()

# 15.
f4 = open("daily_status_report.txt","a")
f4.write("HI")
f5 = open("daily_status_report.txt","r")
f5.read()